import Head from "next/head";

import { useUser } from "../lib/UserContext";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  /*
   * Check if a user is defined (a user is logged in)
   * if `session` is defined, we change the route to '/dashboard'
   *
   * for those using nextjs, pages middleware (pages/_middleware.ts) might be
   * a better way to handle protecting routes and redirects
   * https://nextjs.org/docs/middleware
   */
  const { session } = useUser();
  if (session) router.push("/dashboard");

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>My to do app</h1>
        <button onClick={() => router.push("/signin")}>Sign in</button>
        <button onClick={() => router.push("/signup")}>Sign up</button>
      </main>
    </div>
  );
}
